//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.12 at 03:44:46 PM BRT 
//


package com.t2tierp.cadastros.empresa;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import org.openswing.swing.message.receive.java.ValueObjectImpl;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}campo1"/>
 *         &lt;element ref="{}valor1"/>
 *         &lt;element ref="{}campo2"/>
 *         &lt;element ref="{}valor2"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "campo1",
    "valor1",
    "campo2",
    "valor2"
})
@XmlRootElement(name = "dados")
public class Dados extends ValueObjectImpl {

    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String campo1;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String valor1;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String campo2;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String valor2;

    /**
     * Gets the value of the campo1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCampo1() {
        return campo1;
    }

    /**
     * Sets the value of the campo1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCampo1(String value) {
        this.campo1 = value;
    }

    /**
     * Gets the value of the valor1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValor1() {
        return valor1;
    }

    /**
     * Sets the value of the valor1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValor1(String value) {
        this.valor1 = value;
    }

    /**
     * Gets the value of the campo2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCampo2() {
        return campo2;
    }

    /**
     * Sets the value of the campo2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCampo2(String value) {
        this.campo2 = value;
    }

    /**
     * Gets the value of the valor2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValor2() {
        return valor2;
    }

    /**
     * Sets the value of the valor2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValor2(String value) {
        this.valor2 = value;
    }

}
