/*
SQLyog Ultimate v8.6 Beta2
MySQL - 5.1.49-community : Database - t2tipafecfjava
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE DATABASE /*!32312 IF NOT EXISTS*/`t2tipafecfjava` /*!40100 DEFAULT CHARACTER SET latin1 */;

USE `t2tipafecfjava`;

/*Table structure for table `banco` */

DROP TABLE IF EXISTS `banco`;

CREATE TABLE `banco` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `CODIGO` int(10) unsigned DEFAULT NULL,
  `NOME` varchar(100) DEFAULT NULL,
  `URL` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `cfop` */

DROP TABLE IF EXISTS `cfop`;

CREATE TABLE `cfop` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `CFOP` int(10) unsigned DEFAULT NULL,
  `DESCRICAO` text,
  `APLICACAO` text,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=542 DEFAULT CHARSET=latin1;

/*Table structure for table `cliente` */

DROP TABLE IF EXISTS `cliente`;

CREATE TABLE `cliente` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `ID_SITUACAO_CLIENTE` int(10) unsigned NOT NULL,
  `NOME` varchar(150) DEFAULT NULL,
  `FANTASIA` varchar(150) DEFAULT NULL,
  `EMAIL` varchar(250) DEFAULT NULL,
  `CPF_CNPJ` varchar(14) DEFAULT NULL,
  `RG` varchar(20) DEFAULT NULL,
  `ORGAO_RG` varchar(10) DEFAULT NULL,
  `INSCRICAO_ESTADUAL` varchar(30) DEFAULT NULL,
  `INSCRICAO_MUNICIPAL` varchar(30) DEFAULT NULL,
  `TIPO_PESSOA` char(1) DEFAULT NULL,
  `DATA_CADASTRO` date DEFAULT NULL,
  `DATA_EMISSAO_RG` date DEFAULT NULL,
  `SEXO` char(1) DEFAULT NULL,
  `LOGRADOURO` varchar(250) DEFAULT NULL,
  `NUMERO` varchar(6) DEFAULT NULL,
  `COMPLEMENTO` varchar(50) DEFAULT NULL,
  `CEP` varchar(8) DEFAULT NULL,
  `BAIRRO` varchar(100) DEFAULT NULL,
  `CIDADE` varchar(100) DEFAULT NULL,
  `UF` varchar(2) DEFAULT NULL,
  `FONE1` varchar(10) DEFAULT NULL,
  `FONE2` varchar(10) DEFAULT NULL,
  `CELULAR` varchar(10) DEFAULT NULL,
  `CONTATO` varchar(50) DEFAULT NULL,
  `CODIGO_IBGE_CIDADE` int(10) unsigned DEFAULT NULL,
  `CODIGO_IBGE_UF` int(10) unsigned DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_SITUACAO_CLIENTE` (`ID_SITUACAO_CLIENTE`),
  CONSTRAINT `cliente_ibfk_1` FOREIGN KEY (`ID_SITUACAO_CLIENTE`) REFERENCES `situacao_cliente` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;

/*Table structure for table `dav_cabecalho` */

DROP TABLE IF EXISTS `dav_cabecalho`;

CREATE TABLE `dav_cabecalho` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `ID_PESSOA` int(10) unsigned DEFAULT NULL,
  `ID_EMPRESA` int(10) unsigned DEFAULT NULL,
  `NUMERO_DAV` varchar(10) DEFAULT NULL,
  `NUMERO_ECF` varchar(5) DEFAULT NULL,
  `CCF` int(10) unsigned DEFAULT NULL,
  `COO` int(10) unsigned DEFAULT NULL,
  `NOME_DESTINATARIO` varchar(100) DEFAULT NULL,
  `CPF_CNPJ_DESTINATARIO` varchar(14) DEFAULT NULL,
  `DATA_EMISSAO` date DEFAULT NULL,
  `HORA_EMISSAO` varchar(8) DEFAULT NULL,
  `SITUACAO` char(1) DEFAULT NULL,
  `TAXA_ACRESCIMO` decimal(20,6) DEFAULT NULL,
  `ACRESCIMO` decimal(20,6) DEFAULT NULL,
  `TAXA_DESCONTO` decimal(20,6) DEFAULT NULL,
  `DESCONTO` decimal(20,6) DEFAULT NULL,
  `SUBTOTAL` decimal(20,6) DEFAULT NULL,
  `VALOR` decimal(20,6) DEFAULT NULL,
  `IMPRESSO` char(1) DEFAULT NULL,
  `HASH_TRIPA` varchar(32) DEFAULT NULL,
  `HASH_INCREMENTO` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `dav_detalhe` */

DROP TABLE IF EXISTS `dav_detalhe`;

CREATE TABLE `dav_detalhe` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `ID_DAV_CABECALHO` int(10) unsigned NOT NULL,
  `ID_PRODUTO` int(10) unsigned NOT NULL,
  `NUMERO_DAV` varchar(10) DEFAULT NULL,
  `DATA_EMISSAO` date DEFAULT NULL,
  `ITEM` int(10) unsigned DEFAULT NULL,
  `QUANTIDADE` decimal(20,6) DEFAULT NULL,
  `VALOR_UNITARIO` decimal(20,6) DEFAULT NULL,
  `VALOR_TOTAL` decimal(20,6) DEFAULT NULL,
  `CANCELADO` char(1) DEFAULT NULL,
  `MESCLA_PRODUTO` char(1) DEFAULT NULL,
  `GTIN_PRODUTO` varchar(14) DEFAULT NULL,
  `NOME_PRODUTO` varchar(100) DEFAULT NULL,
  `UNIDADE_PRODUTO` varchar(10) DEFAULT NULL,
  `TOTALIZADOR_PARCIAL` varchar(10) DEFAULT NULL,
  `HASH_TRIPA` varchar(32) DEFAULT NULL,
  `HASH_INCREMENTO` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_DAV_CAB_DET` (`ID_DAV_CABECALHO`),
  KEY `FK_PRODUTO_DAV_DET` (`ID_PRODUTO`),
  CONSTRAINT `dav_detalhe_ibfk_1` FOREIGN KEY (`ID_DAV_CABECALHO`) REFERENCES `dav_cabecalho` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `dav_detalhe_ibfk_2` FOREIGN KEY (`ID_PRODUTO`) REFERENCES `produto` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `ecf_caixa` */

DROP TABLE IF EXISTS `ecf_caixa`;

CREATE TABLE `ecf_caixa` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `NOME` varchar(30) DEFAULT NULL,
  `DATA_CADASTRO` date DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;

/*Table structure for table `ecf_cheque_cliente` */

DROP TABLE IF EXISTS `ecf_cheque_cliente`;

CREATE TABLE `ecf_cheque_cliente` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `ID_BANCO` int(10) unsigned NOT NULL,
  `ID_CLIENTE` int(10) unsigned NOT NULL,
  `NUMERO_CHEQUE` int(10) unsigned DEFAULT NULL,
  `DATA_CHEQUE` date DEFAULT NULL,
  `VALOR_CHEQUE` decimal(20,6) DEFAULT NULL,
  `OBSERVACOES` text,
  PRIMARY KEY (`ID`),
  KEY `FK_CLIENTE_CHEQUE` (`ID_CLIENTE`),
  KEY `FK_BANCO_CHEQUE` (`ID_BANCO`),
  CONSTRAINT `ecf_cheque_cliente_ibfk_1` FOREIGN KEY (`ID_CLIENTE`) REFERENCES `cliente` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `ecf_cheque_cliente_ibfk_2` FOREIGN KEY (`ID_BANCO`) REFERENCES `banco` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `ecf_configuracao` */

DROP TABLE IF EXISTS `ecf_configuracao`;

CREATE TABLE `ecf_configuracao` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `ID_ECF_IMPRESSORA` int(10) unsigned NOT NULL,
  `ID_ECF_RESOLUCAO` int(10) unsigned NOT NULL,
  `ID_ECF_CAIXA` int(10) unsigned NOT NULL,
  `ID_ECF_EMPRESA` int(10) unsigned NOT NULL,
  `MENSAGEM_CUPOM` varchar(250) DEFAULT NULL,
  `PORTA_ECF` char(10) DEFAULT NULL,
  `PORTA_PINPAD` char(10) DEFAULT NULL,
  `PORTA_BALANCA` char(10) DEFAULT NULL,
  `IP_SERVIDOR` varchar(15) DEFAULT NULL,
  `IP_SITEF` varchar(15) DEFAULT NULL,
  `TIPO_TEF` char(2) DEFAULT NULL,
  `TITULO_TELA_CAIXA` varchar(100) DEFAULT NULL,
  `CAMINHO_IMAGENS_PRODUTOS` varchar(250) DEFAULT NULL,
  `CAMINHO_IMAGENS_MARKETING` varchar(250) DEFAULT NULL,
  `CAMINHO_IMAGENS_LAYOUT` varchar(250) DEFAULT NULL,
  `COR_JANELAS_INTERNAS` varchar(20) DEFAULT NULL,
  `MARKETING_ATIVO` char(1) DEFAULT NULL,
  `CFOP_ECF` int(10) unsigned DEFAULT NULL,
  `CFOP_NF2` int(10) unsigned DEFAULT NULL,
  `TIMEOUT_ECF` int(10) unsigned DEFAULT NULL,
  `INTERVALO_ECF` int(10) unsigned DEFAULT NULL,
  `DESCRICAO_SUPRIMENTO` varchar(20) DEFAULT NULL,
  `DESCRICAO_SANGRIA` varchar(20) DEFAULT NULL,
  `TEF_TIPO_GP` int(10) unsigned DEFAULT NULL,
  `TEF_TEMPO_ESPERA` int(10) unsigned DEFAULT NULL,
  `TEF_ESPERA_STS` int(10) unsigned DEFAULT NULL,
  `TEF_NUMERO_VIAS` int(10) unsigned DEFAULT NULL,
  `INDICE_GERENCIAL_DAV` int(10) unsigned DEFAULT NULL,
  `DECIMAIS_QUANTIDADE` int(10) unsigned DEFAULT NULL,
  `DECIMAIS_VALOR` int(10) unsigned DEFAULT NULL,
  `SINCRONIZADO` char(1) DEFAULT NULL,
  `GERENCIAL_MEIOS_PAGAMENTO` int(10) unsigned DEFAULT NULL,
  `GERENCIAL_IDENTIFICACAO_PAF` int(10) unsigned DEFAULT NULL,
  `GERENCIAL_PARAMETROS_CONFIGURACAO` int(10) unsigned DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_EMPRESA_CONFIGURACAO` (`ID_ECF_EMPRESA`),
  KEY `FK_CAIXA_CONFIGURACAO` (`ID_ECF_CAIXA`),
  KEY `FK_RESOLUCAO_CONFIGURACAO` (`ID_ECF_RESOLUCAO`),
  KEY `FK_IMPRESSORA_CONFIGURACAO` (`ID_ECF_IMPRESSORA`),
  CONSTRAINT `ecf_configuracao_ibfk_1` FOREIGN KEY (`ID_ECF_EMPRESA`) REFERENCES `ecf_empresa` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `ecf_configuracao_ibfk_2` FOREIGN KEY (`ID_ECF_CAIXA`) REFERENCES `ecf_caixa` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `ecf_configuracao_ibfk_3` FOREIGN KEY (`ID_ECF_RESOLUCAO`) REFERENCES `ecf_resolucao` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `ecf_configuracao_ibfk_4` FOREIGN KEY (`ID_ECF_IMPRESSORA`) REFERENCES `ecf_impressora` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;

/*Table structure for table `ecf_contador` */

DROP TABLE IF EXISTS `ecf_contador`;

CREATE TABLE `ecf_contador` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `ID_ECF_EMPRESA` int(10) unsigned NOT NULL,
  `CPF` varchar(11) DEFAULT NULL,
  `CNPJ` varchar(14) DEFAULT NULL,
  `NOME` varchar(100) DEFAULT NULL,
  `INSCRICAO_CRC` varchar(15) DEFAULT NULL,
  `FONE` varchar(15) DEFAULT NULL,
  `FAX` varchar(15) DEFAULT NULL,
  `LOGRADOURO` varchar(100) DEFAULT NULL,
  `NUMERO` int(10) unsigned DEFAULT NULL,
  `COMPLEMENTO` varchar(100) DEFAULT NULL,
  `BAIRRO` varchar(30) DEFAULT NULL,
  `CEP` varchar(8) DEFAULT NULL,
  `CODIGO_MUNICIPIO` int(10) unsigned DEFAULT NULL,
  `UF` char(2) DEFAULT NULL,
  `EMAIL` varchar(250) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_EMPRESA_CONTADOR` (`ID_ECF_EMPRESA`),
  CONSTRAINT `ecf_contador_ibfk_1` FOREIGN KEY (`ID_ECF_EMPRESA`) REFERENCES `ecf_empresa` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `ecf_documentos_emitidos` */

DROP TABLE IF EXISTS `ecf_documentos_emitidos`;

CREATE TABLE `ecf_documentos_emitidos` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `ID_ECF_MOVIMENTO` int(10) unsigned NOT NULL,
  `DATA_EMISSAO` date DEFAULT NULL,
  `HORA_EMISSAO` varchar(8) DEFAULT NULL,
  `TIPO` char(2) DEFAULT NULL,
  `COO` int(10) unsigned DEFAULT NULL,
  `SINCRONIZADO` char(1) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_MOVIMENTO_DOC_EMITIDOS` (`ID_ECF_MOVIMENTO`),
  CONSTRAINT `ecf_documentos_emitidos_ibfk_1` FOREIGN KEY (`ID_ECF_MOVIMENTO`) REFERENCES `ecf_movimento` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `ecf_empresa` */

DROP TABLE IF EXISTS `ecf_empresa`;

CREATE TABLE `ecf_empresa` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `ID_EMPRESA` int(10) unsigned NOT NULL,
  `RAZAO_SOCIAL` varchar(150) DEFAULT NULL,
  `NOME_FANTASIA` varchar(150) DEFAULT NULL,
  `CNPJ` varchar(14) DEFAULT NULL,
  `INSCRICAO_ESTADUAL` varchar(30) DEFAULT NULL,
  `INSCRICAO_MUNICIPAL` varchar(30) DEFAULT NULL,
  `MATRIZ_FILIAL` char(1) DEFAULT NULL,
  `DATA_CADASTRO` date DEFAULT NULL,
  `LOGRADOURO` varchar(100) DEFAULT NULL,
  `NUMERO` varchar(10) DEFAULT NULL,
  `COMPLEMENTO` varchar(100) DEFAULT NULL,
  `BAIRRO` varchar(50) DEFAULT NULL,
  `CIDADE` varchar(50) DEFAULT NULL,
  `CODIGO_IBGE_CIDADE` int(10) unsigned DEFAULT NULL,
  `CODIGO_IBGE_UF` int(10) unsigned DEFAULT NULL,
  `UF` char(2) DEFAULT NULL,
  `CEP` varchar(8) DEFAULT NULL,
  `FONE` varchar(10) DEFAULT NULL,
  `FAX` varchar(10) DEFAULT NULL,
  `CONTATO` varchar(30) DEFAULT NULL,
  `SUFRAMA` varchar(9) DEFAULT NULL,
  `EMAIL` varchar(250) DEFAULT NULL,
  `INSCRICAO_ESTADUAL_ST` varchar(30) DEFAULT NULL,
  `INSCRICAO_JUNTA_COMERCIAL` varchar(30) DEFAULT NULL,
  `DATA_INSC_JUNTA_COMERCIAL` date DEFAULT NULL,
  `DATA_INICIO_ATIVIDADES` date DEFAULT NULL,
  `IMAGEM_LOGOTIPO` text,
  `CRT` char(1) DEFAULT NULL,
  `TIPO_REGIME` char(1) DEFAULT NULL,
  `ALIQUOTA_PIS` decimal(20,6) DEFAULT NULL,
  `ALIQUOTA_COFINS` decimal(20,6) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_EMPRESA_FILIAL` (`ID_EMPRESA`),
  CONSTRAINT `ecf_empresa_ibfk_1` FOREIGN KEY (`ID_EMPRESA`) REFERENCES `ecf_empresa` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;

/*Table structure for table `ecf_estoque` */

DROP TABLE IF EXISTS `ecf_estoque`;

CREATE TABLE `ecf_estoque` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `ID_ECF_EMPRESA` int(10) unsigned NOT NULL,
  `ID_ECF_IMPRESSORA` int(10) unsigned NOT NULL,
  `NUMERO_SERIE_ECF` varchar(20) DEFAULT NULL,
  `DATA_ATUALIZACAO` date DEFAULT NULL,
  `HORA_ATUALIZACAO` varchar(8) DEFAULT NULL,
  `HASH_TRIPA` varchar(32) DEFAULT NULL,
  `HASH_INCREMENTO` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `ECF_ESTOQUE_FKIndex1` (`ID_ECF_IMPRESSORA`),
  KEY `ECF_ESTOQUE_FKIndex2` (`ID_ECF_EMPRESA`),
  CONSTRAINT `ecf_estoque_ibfk_1` FOREIGN KEY (`ID_ECF_IMPRESSORA`) REFERENCES `ecf_impressora` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `ecf_estoque_ibfk_2` FOREIGN KEY (`ID_ECF_EMPRESA`) REFERENCES `ecf_empresa` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;

/*Table structure for table `ecf_funcionario` */

DROP TABLE IF EXISTS `ecf_funcionario`;

CREATE TABLE `ecf_funcionario` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `NOME` varchar(100) DEFAULT NULL,
  `TELEFONE` varchar(10) DEFAULT NULL,
  `CELULAR` varchar(10) DEFAULT NULL,
  `EMAIL` varchar(250) DEFAULT NULL,
  `COMISSAO_VISTA` decimal(20,6) DEFAULT NULL,
  `COMISSAO_PRAZO` decimal(20,6) DEFAULT NULL,
  `NIVEL_AUTORIZACAO` char(1) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=latin1;

/*Table structure for table `ecf_impressora` */

DROP TABLE IF EXISTS `ecf_impressora`;

CREATE TABLE `ecf_impressora` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `NUMERO` int(10) unsigned DEFAULT NULL,
  `CODIGO` varchar(10) DEFAULT NULL,
  `SERIE` varchar(20) DEFAULT NULL,
  `IDENTIFICACAO` varchar(250) DEFAULT NULL,
  `MC` char(2) DEFAULT NULL,
  `MD` char(2) DEFAULT NULL,
  `VR` char(2) DEFAULT NULL,
  `TIPO` varchar(7) DEFAULT NULL,
  `MARCA` varchar(30) DEFAULT NULL,
  `MODELO` varchar(30) DEFAULT NULL,
  `MODELO_ACBR` varchar(30) DEFAULT NULL,
  `MODELO_DOCUMENTO_FISCAL` char(2) DEFAULT NULL,
  `VERSAO` varchar(30) DEFAULT NULL,
  `LE` char(1) DEFAULT NULL,
  `LEF` char(1) DEFAULT NULL,
  `MFD` char(1) DEFAULT NULL,
  `LACRE_NA_MFD` char(1) DEFAULT NULL,
  `DOCTO` varchar(60) DEFAULT NULL,
  `DATA_INSTALACAO_SB` date DEFAULT NULL,
  `HORA_INSTALACAO_SB` varchar(8) DEFAULT NULL,
  `NUMERO_ECF` varchar(5) DEFAULT NULL,
  `MF_ADICIONAL` char(1) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;

/*Table structure for table `ecf_movimento` */

DROP TABLE IF EXISTS `ecf_movimento`;

CREATE TABLE `ecf_movimento` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `ID_ECF_EMPRESA` int(10) unsigned NOT NULL,
  `ID_ECF_TURNO` int(10) unsigned NOT NULL,
  `ID_ECF_IMPRESSORA` int(10) unsigned NOT NULL,
  `ID_ECF_OPERADOR` int(10) unsigned NOT NULL,
  `ID_ECF_CAIXA` int(10) unsigned NOT NULL,
  `ID_GERENTE_SUPERVISOR` int(10) unsigned NOT NULL,
  `DATA_ABERTURA` date DEFAULT NULL,
  `HORA_ABERTURA` varchar(8) DEFAULT NULL,
  `DATA_FECHAMENTO` date DEFAULT NULL,
  `HORA_FECHAMENTO` varchar(8) DEFAULT NULL,
  `TOTAL_SUPRIMENTO` decimal(20,6) DEFAULT NULL,
  `TOTAL_SANGRIA` decimal(20,6) DEFAULT NULL,
  `TOTAL_NAO_FISCAL` decimal(20,6) DEFAULT NULL,
  `TOTAL_VENDA` decimal(20,6) DEFAULT NULL,
  `TOTAL_DESCONTO` decimal(20,6) DEFAULT NULL,
  `TOTAL_ACRESCIMO` decimal(20,6) DEFAULT NULL,
  `TOTAL_FINAL` decimal(20,6) DEFAULT NULL,
  `TOTAL_RECEBIDO` decimal(20,6) DEFAULT NULL,
  `TOTAL_TROCO` decimal(20,6) DEFAULT NULL,
  `TOTAL_CANCELADO` decimal(20,6) DEFAULT NULL,
  `STATUS_MOVIMENTO` char(1) NOT NULL,
  `SINCRONIZADO` char(1) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_CAIXA_MOVIMENTO` (`ID_ECF_CAIXA`),
  KEY `FK_OPERADOR_MOVIMENTO` (`ID_ECF_OPERADOR`),
  KEY `FK_TURNO_MOVIMENTO` (`ID_ECF_TURNO`),
  KEY `FK_IMPRESSORA_MOVIMENTO` (`ID_ECF_IMPRESSORA`),
  KEY `ECF_MOVIMENTO_FKIndex5` (`ID_ECF_EMPRESA`),
  CONSTRAINT `ecf_movimento_ibfk_1` FOREIGN KEY (`ID_ECF_CAIXA`) REFERENCES `ecf_caixa` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `ecf_movimento_ibfk_2` FOREIGN KEY (`ID_ECF_OPERADOR`) REFERENCES `ecf_operador` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `ecf_movimento_ibfk_3` FOREIGN KEY (`ID_ECF_TURNO`) REFERENCES `ecf_turno` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `ecf_movimento_ibfk_4` FOREIGN KEY (`ID_ECF_IMPRESSORA`) REFERENCES `ecf_impressora` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `ecf_movimento_ibfk_5` FOREIGN KEY (`ID_ECF_EMPRESA`) REFERENCES `ecf_empresa` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;

/*Table structure for table `ecf_operador` */

DROP TABLE IF EXISTS `ecf_operador`;

CREATE TABLE `ecf_operador` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `ID_ECF_FUNCIONARIO` int(10) unsigned NOT NULL,
  `LOGIN` varchar(20) DEFAULT NULL,
  `SENHA` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_FUNCIONARIO_OPERADOR` (`ID_ECF_FUNCIONARIO`),
  CONSTRAINT `ecf_operador_ibfk_1` FOREIGN KEY (`ID_ECF_FUNCIONARIO`) REFERENCES `ecf_funcionario` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=latin1;

/*Table structure for table `ecf_posicao_componentes` */

DROP TABLE IF EXISTS `ecf_posicao_componentes`;

CREATE TABLE `ecf_posicao_componentes` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `ID_ECF_RESOLUCAO` int(10) unsigned NOT NULL,
  `NOME` varchar(100) DEFAULT NULL,
  `ALTURA` int(10) unsigned DEFAULT NULL,
  `LARGURA` int(10) unsigned DEFAULT NULL,
  `TOPO` int(10) unsigned DEFAULT NULL,
  `ESQUERDA` int(10) unsigned DEFAULT NULL,
  `TAMANHO_FONTE` int(10) unsigned DEFAULT '0',
  `TEXTO` varchar(250) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_RESOLUCAO_POSICAO_COMPONENTES` (`ID_ECF_RESOLUCAO`),
  CONSTRAINT `ecf_posicao_componentes_ibfk_1` FOREIGN KEY (`ID_ECF_RESOLUCAO`) REFERENCES `ecf_resolucao` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=114 DEFAULT CHARSET=latin1;

/*Table structure for table `ecf_pre_venda_cabecalho` */

DROP TABLE IF EXISTS `ecf_pre_venda_cabecalho`;

CREATE TABLE `ecf_pre_venda_cabecalho` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `DATA_PV` date DEFAULT NULL,
  `HORA_PV` varchar(8) DEFAULT NULL,
  `SITUACAO` char(1) DEFAULT NULL,
  `CCF` int(10) unsigned DEFAULT NULL,
  `VALOR` decimal(20,6) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `ecf_pre_venda_detalhe` */

DROP TABLE IF EXISTS `ecf_pre_venda_detalhe`;

CREATE TABLE `ecf_pre_venda_detalhe` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `ID_PRODUTO` int(10) unsigned NOT NULL,
  `ID_ECF_PRE_VENDA_CABECALHO` int(10) unsigned NOT NULL,
  `QUANTIDADE` decimal(20,6) DEFAULT NULL,
  `VALOR_UNITARIO` decimal(20,6) DEFAULT NULL,
  `VALOR_TOTAL` decimal(20,6) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_PV_CAB_DET` (`ID_ECF_PRE_VENDA_CABECALHO`),
  KEY `FK_PRODUTO_PV_DET` (`ID_PRODUTO`),
  CONSTRAINT `ecf_pre_venda_detalhe_ibfk_1` FOREIGN KEY (`ID_ECF_PRE_VENDA_CABECALHO`) REFERENCES `ecf_pre_venda_cabecalho` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `ecf_pre_venda_detalhe_ibfk_2` FOREIGN KEY (`ID_PRODUTO`) REFERENCES `produto` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `ecf_recebimento_nao_fiscal` */

DROP TABLE IF EXISTS `ecf_recebimento_nao_fiscal`;

CREATE TABLE `ecf_recebimento_nao_fiscal` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `ID_ECF_MOVIMENTO` int(10) unsigned NOT NULL,
  `DATA_RECBTO` date DEFAULT NULL,
  `DESCRICAO` varchar(50) DEFAULT NULL,
  `VALOR` decimal(20,6) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_MOVIMENTO_RECBTO_NAO_FISCAL` (`ID_ECF_MOVIMENTO`),
  CONSTRAINT `ecf_recebimento_nao_fiscal_ibfk_1` FOREIGN KEY (`ID_ECF_MOVIMENTO`) REFERENCES `ecf_movimento` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `ecf_resolucao` */

DROP TABLE IF EXISTS `ecf_resolucao`;

CREATE TABLE `ecf_resolucao` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `RESOLUCAO_TELA` varchar(20) DEFAULT NULL,
  `LARGURA` int(10) unsigned DEFAULT NULL,
  `ALTURA` int(10) unsigned DEFAULT NULL,
  `IMAGEM_TELA` varchar(50) DEFAULT NULL,
  `IMAGEM_MENU` varchar(50) DEFAULT NULL,
  `IMAGEM_SUBMENU` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=latin1;

/*Table structure for table `ecf_sangria` */

DROP TABLE IF EXISTS `ecf_sangria`;

CREATE TABLE `ecf_sangria` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `ID_ECF_MOVIMENTO` int(10) unsigned NOT NULL,
  `DATA_SANGRIA` date DEFAULT NULL,
  `VALOR` decimal(20,6) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_MOVIMENTO_SANGRIA` (`ID_ECF_MOVIMENTO`),
  CONSTRAINT `ecf_sangria_ibfk_1` FOREIGN KEY (`ID_ECF_MOVIMENTO`) REFERENCES `ecf_movimento` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `ecf_suprimento` */

DROP TABLE IF EXISTS `ecf_suprimento`;

CREATE TABLE `ecf_suprimento` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `ID_ECF_MOVIMENTO` int(10) unsigned NOT NULL,
  `DATA_SUPRIMENTO` date DEFAULT NULL,
  `VALOR` decimal(20,6) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_MOVIMENTO_SUPRIMENTO` (`ID_ECF_MOVIMENTO`),
  CONSTRAINT `ecf_suprimento_ibfk_1` FOREIGN KEY (`ID_ECF_MOVIMENTO`) REFERENCES `ecf_movimento` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `ecf_tipo_pagamento` */

DROP TABLE IF EXISTS `ecf_tipo_pagamento`;

CREATE TABLE `ecf_tipo_pagamento` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `CODIGO` char(3) DEFAULT NULL,
  `DESCRICAO` varchar(20) DEFAULT NULL,
  `TEF` char(1) DEFAULT NULL,
  `IMPRIME_VINCULADO` char(1) DEFAULT NULL,
  `PERMITE_TROCO` char(1) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=latin1;

/*Table structure for table `ecf_total_tipo_pgto` */

DROP TABLE IF EXISTS `ecf_total_tipo_pgto`;

CREATE TABLE `ecf_total_tipo_pgto` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `ID_ECF_VENDA_CABECALHO` int(10) unsigned NOT NULL,
  `ID_ECF_TIPO_PAGAMENTO` int(10) unsigned NOT NULL,
  `VALOR` decimal(20,6) DEFAULT NULL,
  `NSU` varchar(30) DEFAULT NULL,
  `ESTORNO` char(1) DEFAULT NULL,
  `REDE` varchar(10) DEFAULT NULL,
  `CARTAO_DC` char(1) DEFAULT NULL,
  `SERIE_ECF` varchar(20) DEFAULT NULL,
  `COO` int(10) unsigned DEFAULT NULL,
  `CCF` int(10) unsigned DEFAULT NULL,
  `GNF` int(10) unsigned DEFAULT NULL,
  `SINCRONIZADO` char(1) DEFAULT NULL,
  `HASH_TRIPA` varchar(32) DEFAULT NULL,
  `HASH_INCREMENTO` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_TIPO_PGTO_TOTAL` (`ID_ECF_TIPO_PAGAMENTO`),
  KEY `FK_VENDA_CAB_TOTAL_TIPO_PGTO` (`ID_ECF_VENDA_CABECALHO`),
  CONSTRAINT `ecf_total_tipo_pgto_ibfk_1` FOREIGN KEY (`ID_ECF_TIPO_PAGAMENTO`) REFERENCES `ecf_tipo_pagamento` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `ecf_total_tipo_pgto_ibfk_2` FOREIGN KEY (`ID_ECF_VENDA_CABECALHO`) REFERENCES `ecf_venda_cabecalho` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=latin1;

/*Table structure for table `ecf_turno` */

DROP TABLE IF EXISTS `ecf_turno`;

CREATE TABLE `ecf_turno` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `DESCRICAO` varchar(10) DEFAULT NULL,
  `HORA_INICIO` varchar(8) DEFAULT NULL,
  `HORA_FIM` varchar(8) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=latin1;

/*Table structure for table `ecf_venda_cabecalho` */

DROP TABLE IF EXISTS `ecf_venda_cabecalho`;

CREATE TABLE `ecf_venda_cabecalho` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `ID_ECF_DAV` int(10) unsigned DEFAULT NULL,
  `ID_ECF_PRE_VENDA_CABECALHO` int(10) unsigned DEFAULT NULL,
  `ID_CLIENTE` int(10) unsigned DEFAULT NULL,
  `ID_ECF_FUNCIONARIO` int(10) unsigned DEFAULT NULL,
  `ID_ECF_MOVIMENTO` int(10) unsigned NOT NULL,
  `SERIE_ECF` varchar(20) DEFAULT NULL,
  `CFOP` int(10) unsigned DEFAULT NULL,
  `COO` int(10) unsigned DEFAULT NULL,
  `CCF` int(10) unsigned DEFAULT NULL,
  `DATA_VENDA` date DEFAULT NULL,
  `HORA_VENDA` varchar(8) DEFAULT NULL,
  `VALOR_VENDA` decimal(20,6) DEFAULT NULL,
  `TAXA_DESCONTO` decimal(20,6) DEFAULT NULL,
  `DESCONTO` decimal(20,6) DEFAULT NULL,
  `TAXA_ACRESCIMO` decimal(20,6) DEFAULT NULL,
  `ACRESCIMO` decimal(20,6) DEFAULT NULL,
  `VALOR_FINAL` decimal(20,6) DEFAULT NULL,
  `VALOR_RECEBIDO` decimal(20,6) DEFAULT NULL,
  `TROCO` decimal(20,6) DEFAULT NULL,
  `VALOR_CANCELADO` decimal(20,6) DEFAULT NULL,
  `SINCRONIZADO` char(1) DEFAULT NULL,
  `TOTAL_PRODUTOS` decimal(20,6) DEFAULT NULL,
  `TOTAL_DOCUMENTO` decimal(20,6) DEFAULT NULL,
  `BASE_ICMS` decimal(20,6) DEFAULT NULL,
  `ICMS` decimal(20,6) DEFAULT NULL,
  `ICMS_OUTRAS` decimal(20,6) DEFAULT NULL,
  `ISSQN` decimal(20,6) DEFAULT NULL,
  `PIS` decimal(20,6) DEFAULT NULL,
  `COFINS` decimal(20,6) DEFAULT NULL,
  `ACRESCIMO_ITENS` decimal(20,6) DEFAULT NULL,
  `DESCONTO_ITENS` decimal(20,6) DEFAULT NULL,
  `STATUS_VENDA` char(1) DEFAULT NULL,
  `NOME_CLIENTE` varchar(100) DEFAULT NULL,
  `CPF_CNPJ_CLIENTE` varchar(14) DEFAULT NULL,
  `CUPOM_CANCELADO` char(1) DEFAULT NULL,
  `HASH_TRIPA` varchar(32) DEFAULT NULL,
  `HASH_INCREMENTO` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_MOVIMENTO_VENDA_CAB` (`ID_ECF_MOVIMENTO`),
  KEY `FK_VENDEDOR_VENDA` (`ID_ECF_FUNCIONARIO`),
  KEY `FK_CLIENTE_VENDA` (`ID_CLIENTE`),
  KEY `FK_PV_VENDA` (`ID_ECF_PRE_VENDA_CABECALHO`),
  KEY `FK_DAV_VENDA` (`ID_ECF_DAV`),
  CONSTRAINT `ecf_venda_cabecalho_ibfk_1` FOREIGN KEY (`ID_ECF_MOVIMENTO`) REFERENCES `ecf_movimento` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `ecf_venda_cabecalho_ibfk_2` FOREIGN KEY (`ID_ECF_FUNCIONARIO`) REFERENCES `ecf_funcionario` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `ecf_venda_cabecalho_ibfk_3` FOREIGN KEY (`ID_CLIENTE`) REFERENCES `cliente` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `ecf_venda_cabecalho_ibfk_4` FOREIGN KEY (`ID_ECF_PRE_VENDA_CABECALHO`) REFERENCES `ecf_pre_venda_cabecalho` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `ecf_venda_cabecalho_ibfk_5` FOREIGN KEY (`ID_ECF_DAV`) REFERENCES `dav_cabecalho` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=latin1;

/*Table structure for table `ecf_venda_detalhe` */

DROP TABLE IF EXISTS `ecf_venda_detalhe`;

CREATE TABLE `ecf_venda_detalhe` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `ID_ECF_PRODUTO` int(10) unsigned NOT NULL,
  `ID_ECF_VENDA_CABECALHO` int(10) unsigned NOT NULL,
  `CFOP` int(10) unsigned DEFAULT NULL,
  `ITEM` int(10) unsigned DEFAULT NULL,
  `QUANTIDADE` decimal(20,6) DEFAULT NULL,
  `VALOR_UNITARIO` decimal(20,6) DEFAULT NULL,
  `VALOR_TOTAL` decimal(20,6) DEFAULT NULL,
  `TOTAL_ITEM` decimal(20,6) DEFAULT NULL,
  `BASE_ICMS` decimal(20,6) DEFAULT NULL,
  `TAXA_ICMS` decimal(20,6) DEFAULT NULL,
  `ICMS` decimal(20,6) DEFAULT NULL,
  `TAXA_DESCONTO` decimal(20,6) DEFAULT NULL,
  `DESCONTO` decimal(20,6) DEFAULT NULL,
  `TAXA_ISSQN` decimal(20,6) unsigned zerofill DEFAULT NULL,
  `ISSQN` decimal(20,6) DEFAULT NULL,
  `TAXA_PIS` decimal(20,6) DEFAULT NULL,
  `PIS` decimal(20,6) DEFAULT NULL,
  `TAXA_COFINS` decimal(20,6) DEFAULT NULL,
  `COFINS` decimal(20,6) DEFAULT NULL,
  `TAXA_ACRESCIMO` decimal(20,6) DEFAULT NULL,
  `ACRESCIMO` decimal(20,6) DEFAULT NULL,
  `ACRESCIMO_RATEIO` decimal(20,6) DEFAULT NULL,
  `DESCONTO_RATEIO` decimal(20,6) DEFAULT NULL,
  `TOTALIZADOR_PARCIAL` varchar(10) DEFAULT NULL,
  `CST` char(3) DEFAULT NULL,
  `CANCELADO` char(1) DEFAULT NULL,
  `MOVIMENTA_ESTOQUE` char(1) DEFAULT NULL,
  `GTIN` varchar(14) DEFAULT NULL,
  `CCF` int(10) unsigned DEFAULT NULL,
  `COO` int(10) unsigned DEFAULT NULL,
  `SERIE_ECF` varchar(20) DEFAULT NULL,
  `ECF_ICMS_ST` varchar(4) DEFAULT NULL,
  `HASH_TRIPA` varchar(32) DEFAULT NULL,
  `HASH_INCREMENTO` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_VENDA_CAB_DET` (`ID_ECF_VENDA_CABECALHO`),
  KEY `FK_PRODUTO_VENDA_DET` (`ID_ECF_PRODUTO`),
  CONSTRAINT `ecf_venda_detalhe_ibfk_1` FOREIGN KEY (`ID_ECF_VENDA_CABECALHO`) REFERENCES `ecf_venda_cabecalho` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `ecf_venda_detalhe_ibfk_2` FOREIGN KEY (`ID_ECF_PRODUTO`) REFERENCES `produto` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=latin1;

/*Table structure for table `ficha_tecnica` */

DROP TABLE IF EXISTS `ficha_tecnica`;

CREATE TABLE `ficha_tecnica` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `ID_PRODUTO` int(10) unsigned NOT NULL,
  `DESCRICAO` varchar(50) DEFAULT NULL,
  `ID_PRODUTO_FILHO` int(10) unsigned DEFAULT NULL,
  `QUANTIDADE` decimal(20,6) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_PRODUTO_FICHA_TECNICA` (`ID_PRODUTO`),
  CONSTRAINT `ficha_tecnica_ibfk_1` FOREIGN KEY (`ID_PRODUTO`) REFERENCES `produto` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `nfe_cabecalho` */

DROP TABLE IF EXISTS `nfe_cabecalho`;

CREATE TABLE `nfe_cabecalho` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `ID_VENDA_CABECALHO` int(10) unsigned NOT NULL,
  `ID_PEDIDO_COMPRA` int(10) unsigned DEFAULT NULL,
  `ID_CLIENTE` int(10) unsigned DEFAULT NULL,
  `ID_FUNCIONARIO` int(10) unsigned DEFAULT NULL,
  `CODIGO_NUMERICO` varchar(8) DEFAULT NULL,
  `NATUREZA_OPERACAO` varchar(60) DEFAULT NULL,
  `INDICADOR_FORMA_PAGAMENTO` char(1) DEFAULT NULL,
  `CODIGO_MODELO` char(2) DEFAULT NULL,
  `SERIE` char(3) DEFAULT NULL,
  `NUMERO` varchar(9) DEFAULT NULL,
  `DATA_EMISSAO` date DEFAULT NULL,
  `DATA_ENTRADA_SAIDA` date DEFAULT NULL,
  `HORA_ENTRADA_SAIDA` varchar(8) DEFAULT NULL,
  `TIPO_OPERACAO` char(1) DEFAULT NULL,
  `CODIGO_MUNICIPIO` int(10) unsigned DEFAULT NULL,
  `FORMATO_IMPRESSAO_DANFE` char(1) DEFAULT NULL,
  `TIPO_EMISSAO` char(1) DEFAULT NULL,
  `CHAVE_ACESSO` varchar(44) DEFAULT NULL,
  `DIGITO_CHAVE_ACESSO` char(1) DEFAULT NULL,
  `AMBIENTE` char(1) DEFAULT NULL,
  `FINALIDADE_EMISSAO` char(1) DEFAULT NULL,
  `PROCESSO_EMISSAO` char(1) DEFAULT NULL,
  `VERSAO_PROCESSO_EMISSAO` int(10) unsigned DEFAULT NULL,
  `BASE_CALCULO_ICMS` decimal(18,6) DEFAULT NULL,
  `VALOR_ICMS` decimal(18,6) DEFAULT NULL,
  `BASE_CALCULO_ICMS_ST` decimal(18,6) DEFAULT NULL,
  `VALOR_ICMS_ST` decimal(18,6) DEFAULT NULL,
  `VALOR_TOTAL_PRODUTOS` decimal(18,6) DEFAULT NULL,
  `VALOR_FRETE` decimal(18,6) DEFAULT NULL,
  `VALOR_SEGURO` decimal(18,6) DEFAULT NULL,
  `VALOR_DESCONTO` decimal(18,6) DEFAULT NULL,
  `VALOR_IMPOSTO_IMPORTACAO` decimal(18,6) DEFAULT NULL,
  `VALOR_IPI` decimal(18,6) DEFAULT NULL,
  `VALOR_PIS` decimal(18,6) DEFAULT NULL,
  `VALOR_COFINS` decimal(18,6) DEFAULT NULL,
  `VALOR_DESPESAS_ACESSORIAS` decimal(18,6) DEFAULT NULL,
  `VALOR_TOTAL` decimal(18,6) DEFAULT NULL,
  `VALOR_SERVICOS` decimal(18,6) DEFAULT NULL,
  `BASE_CALCULO_ISSQN` decimal(18,6) DEFAULT NULL,
  `VALOR_ISSQN` decimal(18,6) DEFAULT NULL,
  `VALOR_PIS_ISSQN` decimal(18,6) DEFAULT NULL,
  `VALOR_COFINS_ISSQN` decimal(18,6) DEFAULT NULL,
  `VALOR_RETIDO_PIS` decimal(18,6) DEFAULT NULL,
  `VALOR_RETIDO_COFINS` decimal(18,6) DEFAULT NULL,
  `VALOR_RETIDO_CSLL` decimal(18,6) DEFAULT NULL,
  `BASE_CALCULO_IRRF` decimal(18,6) DEFAULT NULL,
  `VALOR_RETIDO_IRRF` decimal(18,6) DEFAULT NULL,
  `BASE_CALCULO_PREVIDENCIA` decimal(18,6) DEFAULT NULL,
  `VALOR_RETIDO_PREVIDENCIA` decimal(18,6) DEFAULT NULL,
  `UF_EMBARQUE` char(2) DEFAULT NULL,
  `LOCAL_EMBARQUE` varchar(60) DEFAULT NULL,
  `NOTA_EMPENHO` varchar(17) DEFAULT NULL,
  `PEDIDO` varchar(60) DEFAULT NULL,
  `ISS_RETIDO` char(1) DEFAULT NULL,
  `INFORMACOES_ADD_FISCO` text,
  `INFORMACOES_ADD_CONTRIBUINTE` text,
  `INFORMACOES_COMPLEMENTARES` text,
  PRIMARY KEY (`ID`),
  KEY `NFE_CABECALHO_FKIndex1` (`ID_VENDA_CABECALHO`),
  CONSTRAINT `nfe_cabecalho_ibfk_1` FOREIGN KEY (`ID_VENDA_CABECALHO`) REFERENCES `ecf_venda_cabecalho` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `nfe_configuracao` */

DROP TABLE IF EXISTS `nfe_configuracao`;

CREATE TABLE `nfe_configuracao` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `CERTIFICADO_DIGITAL` varchar(20) DEFAULT NULL,
  `CAMINHO_CERTIFICADO` varchar(80) DEFAULT NULL,
  `SENHA_CERTIFICADO` varchar(15) DEFAULT NULL,
  `FORMATO_IMPRESSAO_DANFE` char(1) DEFAULT NULL,
  `LOGOMARCA` varchar(80) DEFAULT NULL,
  `CAMINHO_SALVAR_XML` varchar(80) DEFAULT NULL,
  `SALVA_XML` char(1) DEFAULT NULL,
  `FONTE_ATT` int(10) unsigned DEFAULT NULL,
  `FONTE_OUTROS_CAMPOS` int(10) unsigned DEFAULT NULL,
  `FONTE_RAZAO_SOCIAL` int(10) unsigned DEFAULT NULL,
  `IMPRIMIR_DETALHE_ESPECIFICO` int(10) unsigned DEFAULT NULL,
  `UF_WEBSERVICE` char(2) DEFAULT NULL,
  `AMBIENTE` char(1) DEFAULT NULL,
  `NOME_HOST` varchar(30) DEFAULT NULL,
  `PORTA` int(10) unsigned DEFAULT NULL,
  `USUARIO` varchar(60) DEFAULT NULL,
  `SENHA` varchar(20) DEFAULT NULL,
  `ASSUNTO` varchar(80) DEFAULT NULL,
  `AUTENTICA_SSL` char(1) DEFAULT NULL,
  `PROXY_HOST` varchar(80) DEFAULT NULL,
  `PROXY_PORTA` varchar(6) DEFAULT NULL,
  `PROXY_USER` varchar(60) DEFAULT NULL,
  `PROXY_SENHA` varchar(20) DEFAULT NULL,
  `IMPRIMIR_USUARIO_RODAPE` char(1) DEFAULT NULL,
  `TEXTO_EMAIL` text,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `nfe_cupom_fiscal` */

DROP TABLE IF EXISTS `nfe_cupom_fiscal`;

CREATE TABLE `nfe_cupom_fiscal` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `ID_NFE_CABECALHO` int(10) unsigned NOT NULL,
  `MODELO_DOCUMENTO_FISCAL` char(2) DEFAULT NULL,
  `DATA_EMISSAO_CUPOM` date DEFAULT NULL,
  `NUMERO_ORDEM_ECF` int(10) unsigned DEFAULT NULL,
  `COO` int(10) unsigned DEFAULT NULL,
  `NUMERO_CAIXA` int(10) unsigned DEFAULT NULL,
  `NUMERO_SERIE_ECF` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_NFE_CUPOM_FISCAL` (`ID_NFE_CABECALHO`),
  KEY `NFE_CUPOM_FISCAL_FKIndex1` (`ID_NFE_CABECALHO`),
  CONSTRAINT `nfe_cupom_fiscal_ibfk_1` FOREIGN KEY (`ID_NFE_CABECALHO`) REFERENCES `nfe_cabecalho` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `nfe_detalhe` */

DROP TABLE IF EXISTS `nfe_detalhe`;

CREATE TABLE `nfe_detalhe` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `ID_PRODUTO` int(10) unsigned NOT NULL,
  `ID_NFE_CABECALHO` int(10) unsigned NOT NULL,
  `NUMERO_ITEM` int(10) unsigned DEFAULT NULL,
  `CODIGO_PRODUTO` varchar(60) DEFAULT NULL,
  `GTIN` varchar(14) DEFAULT NULL,
  `NOME_PRODUTO` varchar(100) DEFAULT NULL,
  `NCM` varchar(8) DEFAULT NULL,
  `EX_TIPI` int(10) unsigned DEFAULT NULL,
  `CFOP` int(10) unsigned DEFAULT NULL,
  `UNIDADE_COMERCIAL` varchar(6) DEFAULT NULL,
  `QUANTIDADE_COMERCIAL` decimal(18,6) DEFAULT NULL,
  `VALOR_UNITARIO_COMERCIAL` decimal(18,6) DEFAULT NULL,
  `VALOR_BRUTO_PRODUTOS` decimal(18,6) DEFAULT NULL,
  `GTIN_UNIDADE_TRIBUTAVEL` varchar(14) DEFAULT NULL,
  `UNIDADE_TRIBUTAVEL` varchar(6) DEFAULT NULL,
  `QUANTIDADE_TRIBUTAVEL` decimal(18,6) DEFAULT NULL,
  `VALOR_UNITARIO_TRIBUTACAO` decimal(18,6) DEFAULT NULL,
  `VALOR_FRETE` decimal(18,6) DEFAULT NULL,
  `VALOR_SEGURO` decimal(18,6) DEFAULT NULL,
  `VALOR_DESCONTO` decimal(18,6) DEFAULT NULL,
  `VALOR_OUTRAS_DESPESAS` decimal(18,6) DEFAULT NULL,
  `ENTRA_TOTAL` char(1) DEFAULT NULL,
  `ORIGEM_MERCADORIA` char(1) DEFAULT NULL,
  `CST_ICMS` char(3) DEFAULT NULL,
  `CSOSN` char(4) DEFAULT NULL,
  `MODALIDADE_BC_ICMS` char(1) DEFAULT NULL,
  `TAXA_REDUCAO_BC_ICMS` decimal(18,6) DEFAULT NULL,
  `BASE_CALCULO_ICMS` decimal(18,6) DEFAULT NULL,
  `ALIQUOTA_ICMS` decimal(18,6) DEFAULT NULL,
  `VALOR_ICMS` decimal(18,6) DEFAULT NULL,
  `MOTIVO_DESONERACAO_ICMS` char(1) DEFAULT NULL,
  `MODALIDE_BC_ICMS_ST` char(1) DEFAULT NULL,
  `PERCENTUAL_MVA_ICMS_ST` decimal(18,6) DEFAULT NULL,
  `REDUCAO_BC_ICMS_ST` decimal(18,6) DEFAULT NULL,
  `BASE_CALCULO_ICMS_ST` decimal(18,6) DEFAULT NULL,
  `ALIQUOTA_ICMS_ST` decimal(18,6) DEFAULT NULL,
  `VALOR_ICMS_ST` decimal(18,6) DEFAULT NULL,
  `VALOR_BC_ICMS_ST_RETIDO` decimal(18,6) DEFAULT NULL,
  `VALOR_ICMS_ST_RETIDO` decimal(18,6) DEFAULT NULL,
  `ALIQUOTA_CREDITO_ICMS_SN` decimal(18,6) DEFAULT NULL,
  `VALOR_CREDITO_ICMS_SN` decimal(18,6) DEFAULT NULL,
  `ENQUADRAMENTO_IPI` varchar(5) DEFAULT NULL,
  `CNPJ_PRODUTOR` varchar(14) DEFAULT NULL,
  `CODIGO_SELO_IPI` varchar(60) DEFAULT NULL,
  `QUANTIDADE_SELO_IPI` int(10) unsigned DEFAULT NULL,
  `ENQUADRAMENTO_LEGAL_IPI` char(3) DEFAULT NULL,
  `CST_IPI` char(2) DEFAULT NULL,
  `BASE_CALCULO_IPI` decimal(18,6) DEFAULT NULL,
  `ALIQUOTA_IPI` decimal(18,6) DEFAULT NULL,
  `VALOR_IPI` decimal(18,6) DEFAULT NULL,
  `VALOR_BC_II` decimal(18,6) DEFAULT NULL,
  `VALOR_DESPESAS_ADUANEIRAS` decimal(18,6) DEFAULT NULL,
  `VALOR_IMPOSTO_IMPORTACAO` decimal(18,6) DEFAULT NULL,
  `VALOR_IOF` decimal(18,6) DEFAULT NULL,
  `CTS_PIS` char(2) DEFAULT NULL,
  `VALOR_BASE_CALCULO_PIS` decimal(18,6) DEFAULT NULL,
  `ALIQUOTA_PIS_PERCENTUAL` decimal(18,6) DEFAULT NULL,
  `ALIQUOTA_PIS_REAIS` decimal(18,6) DEFAULT NULL,
  `VALOR_PIS` decimal(18,6) DEFAULT NULL,
  `CST_COFINS` char(2) DEFAULT NULL,
  `BASE_CALCULO_COFINS` decimal(18,6) DEFAULT NULL,
  `ALIQUOTA_COFINS_PERCENTUAL` decimal(18,6) DEFAULT NULL,
  `ALIQUOTA_COFINS_REAIS` decimal(18,6) DEFAULT NULL,
  `VALOR_COFINS` decimal(18,6) DEFAULT NULL,
  `BASE_CALCULO_ISSQN` decimal(18,6) DEFAULT NULL,
  `ALIQUOTA_ISSQN` decimal(18,6) DEFAULT NULL,
  `VALOR_ISSQN` decimal(18,6) DEFAULT NULL,
  `MUNICIPIO_ISSQN` int(10) unsigned DEFAULT NULL,
  `ITEM_LISTA_SERVICOS` int(10) unsigned DEFAULT NULL,
  `TRIBUTACAO_ISSQN` char(1) DEFAULT NULL,
  `VALOR_SUBTOTAL` decimal(18,6) DEFAULT NULL,
  `VALOR_TOTAL` decimal(18,6) DEFAULT NULL,
  `INFORMACOES_ADICIONAIS` text,
  PRIMARY KEY (`ID`),
  KEY `FK_NFE_CAB_DET` (`ID_NFE_CABECALHO`),
  KEY `NFE_DETALHE_FKIndex1` (`ID_NFE_CABECALHO`),
  KEY `NFE_DETALHE_FKIndex2` (`ID_PRODUTO`),
  CONSTRAINT `nfe_detalhe_ibfk_1` FOREIGN KEY (`ID_NFE_CABECALHO`) REFERENCES `nfe_cabecalho` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `nfe_detalhe_ibfk_2` FOREIGN KEY (`ID_PRODUTO`) REFERENCES `produto` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `nota_fiscal_cabecalho` */

DROP TABLE IF EXISTS `nota_fiscal_cabecalho`;

CREATE TABLE `nota_fiscal_cabecalho` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `ID_ECF_FUNCIONARIO` int(10) unsigned NOT NULL,
  `ID_CLIENTE` int(10) unsigned NOT NULL,
  `CFOP` int(10) unsigned DEFAULT NULL,
  `NUMERO` varchar(6) DEFAULT NULL,
  `DATA_EMISSAO` date DEFAULT NULL,
  `HORA_EMISSAO` varchar(8) DEFAULT NULL,
  `SERIE` char(2) DEFAULT NULL,
  `SUBSERIE` char(2) DEFAULT NULL,
  `TOTAL_PRODUTOS` decimal(20,6) DEFAULT NULL,
  `TOTAL_NF` decimal(20,6) DEFAULT NULL,
  `BASE_ICMS` decimal(20,6) DEFAULT NULL,
  `ICMS` decimal(20,6) DEFAULT NULL,
  `ICMS_OUTRAS` decimal(20,6) DEFAULT NULL,
  `ISSQN` decimal(20,6) DEFAULT NULL,
  `PIS` decimal(20,6) DEFAULT NULL,
  `COFINS` decimal(20,6) DEFAULT NULL,
  `IPI` decimal(20,6) DEFAULT NULL,
  `TAXA_ACRESCIMO` decimal(20,6) DEFAULT NULL,
  `ACRESCIMO` decimal(20,6) DEFAULT NULL,
  `ACRESCIMO_ITENS` decimal(20,6) DEFAULT NULL,
  `TAXA_DESCONTO` decimal(20,6) DEFAULT NULL,
  `DESCONTO` decimal(20,6) DEFAULT NULL,
  `DESCONTO_ITENS` decimal(20,6) DEFAULT NULL,
  `CANCELADA` char(1) DEFAULT NULL,
  `SINCRONIZADO` char(1) DEFAULT NULL,
  `TIPO_NOTA` char(1) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_CLIENTE_NF2` (`ID_CLIENTE`),
  KEY `FK_VENDEDOR_NF2` (`ID_ECF_FUNCIONARIO`),
  CONSTRAINT `nota_fiscal_cabecalho_ibfk_1` FOREIGN KEY (`ID_CLIENTE`) REFERENCES `cliente` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `nota_fiscal_cabecalho_ibfk_2` FOREIGN KEY (`ID_ECF_FUNCIONARIO`) REFERENCES `ecf_funcionario` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `nota_fiscal_detalhe` */

DROP TABLE IF EXISTS `nota_fiscal_detalhe`;

CREATE TABLE `nota_fiscal_detalhe` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `ID_NF_CABECALHO` int(10) unsigned NOT NULL,
  `ID_PRODUTO` int(10) unsigned NOT NULL,
  `CFOP` int(10) unsigned DEFAULT NULL,
  `ITEM` int(10) unsigned DEFAULT NULL,
  `QUANTIDADE` decimal(20,6) DEFAULT NULL,
  `VALOR_UNITARIO` decimal(20,6) DEFAULT NULL,
  `VALOR_TOTAL` decimal(20,6) DEFAULT NULL,
  `BASE_ICMS` decimal(20,6) DEFAULT NULL,
  `TAXA_ICMS` decimal(20,6) DEFAULT NULL,
  `ICMS` decimal(20,6) DEFAULT NULL,
  `ICMS_OUTRAS` decimal(20,6) DEFAULT NULL,
  `ICMS_ISENTO` decimal(20,6) DEFAULT NULL,
  `TAXA_DESCONTO` decimal(20,6) DEFAULT NULL,
  `DESCONTO` decimal(20,6) DEFAULT NULL,
  `TAXA_ISSQN` decimal(20,6) DEFAULT NULL,
  `ISSQN` decimal(20,6) DEFAULT NULL,
  `TAXA_PIS` decimal(20,6) DEFAULT NULL,
  `PIS` decimal(20,6) DEFAULT NULL,
  `TAXA_COFINS` decimal(20,6) DEFAULT NULL,
  `COFINS` decimal(20,6) DEFAULT NULL,
  `TAXA_ACRESCIMO` decimal(20,6) DEFAULT NULL,
  `ACRESCIMO` decimal(20,6) DEFAULT NULL,
  `TAXA_IPI` decimal(20,6) DEFAULT NULL,
  `IPI` decimal(20,6) DEFAULT NULL,
  `CANCELADO` char(1) DEFAULT NULL,
  `MOVIMENTA_ESTOQUE` char(1) DEFAULT NULL,
  `SINCRONIZADO` char(1) DEFAULT NULL,
  `CST` char(3) DEFAULT NULL,
  `ECF_ICMS_ST` varchar(4) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_NF2_CAB_DET` (`ID_NF_CABECALHO`),
  KEY `FK_PRODUTO_NF2_DET` (`ID_PRODUTO`),
  CONSTRAINT `nota_fiscal_detalhe_ibfk_1` FOREIGN KEY (`ID_NF_CABECALHO`) REFERENCES `nota_fiscal_cabecalho` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `nota_fiscal_detalhe_ibfk_2` FOREIGN KEY (`ID_PRODUTO`) REFERENCES `produto` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `produto` */

DROP TABLE IF EXISTS `produto`;

CREATE TABLE `produto` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `ID_UNIDADE_PRODUTO` int(10) unsigned NOT NULL,
  `GTIN` varchar(14) DEFAULT NULL,
  `CODIGO_INTERNO` varchar(20) DEFAULT NULL,
  `NOME` varchar(100) DEFAULT NULL,
  `DESCRICAO` text,
  `DESCRICAO_PDV` varchar(30) DEFAULT NULL,
  `VALOR_VENDA` decimal(20,6) DEFAULT NULL,
  `QTD_ESTOQUE` decimal(20,6) DEFAULT NULL,
  `QTD_ESTOQUE_ANTERIOR` decimal(20,6) DEFAULT NULL,
  `ESTOQUE_MIN` decimal(20,6) DEFAULT NULL,
  `ESTOQUE_MAX` decimal(20,6) DEFAULT NULL,
  `IAT` char(1) DEFAULT NULL,
  `IPPT` char(1) DEFAULT NULL,
  `NCM` varchar(8) DEFAULT NULL,
  `TIPO_ITEM_SPED` char(2) DEFAULT NULL,
  `DATA_ESTOQUE` date DEFAULT NULL,
  `HORA_ESTOQUE` varchar(8) DEFAULT NULL,
  `TAXA_IPI` decimal(20,6) DEFAULT NULL,
  `TAXA_ISSQN` decimal(20,6) DEFAULT NULL,
  `TAXA_PIS` decimal(20,6) DEFAULT NULL,
  `TAXA_COFINS` decimal(20,6) DEFAULT NULL,
  `TAXA_ICMS` decimal(20,6) DEFAULT NULL,
  `CST` char(3) DEFAULT NULL,
  `CSOSN` char(4) DEFAULT NULL,
  `TOTALIZADOR_PARCIAL` varchar(10) DEFAULT NULL,
  `ECF_ICMS_ST` varchar(4) DEFAULT NULL,
  `CODIGO_BALANCA` int(10) unsigned DEFAULT NULL,
  `PAF_P_ST` char(1) DEFAULT NULL,
  `HASH_TRIPA` varchar(32) DEFAULT NULL,
  `HASH_INCREMENTO` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_UNIDADE_PRODUTO` (`ID_UNIDADE_PRODUTO`),
  CONSTRAINT `produto_ibfk_1` FOREIGN KEY (`ID_UNIDADE_PRODUTO`) REFERENCES `unidade_produto` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=24 DEFAULT CHARSET=latin1;

/*Table structure for table `produto_promocao` */

DROP TABLE IF EXISTS `produto_promocao`;

CREATE TABLE `produto_promocao` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `ID_PRODUTO` int(10) unsigned NOT NULL,
  `DATA_INICIO` date DEFAULT NULL,
  `DATA_FIM` date DEFAULT NULL,
  `QUANTIDADE_EM_PROMOCAO` decimal(20,6) DEFAULT NULL,
  `QUANTIDADE_MAXIMA_CLIENTE` decimal(20,6) DEFAULT NULL,
  `VALOR` decimal(20,6) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_PRODUTO_PROMOCAO` (`ID_PRODUTO`),
  CONSTRAINT `produto_promocao_ibfk_1` FOREIGN KEY (`ID_PRODUTO`) REFERENCES `produto` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `r01` */

DROP TABLE IF EXISTS `r01`;

CREATE TABLE `r01` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `SERIE_ECF` varchar(20) DEFAULT NULL,
  `CNPJ_EMPRESA` varchar(14) DEFAULT NULL,
  `CNPJ_SH` varchar(14) DEFAULT NULL,
  `INSCRICAO_ESTADUAL_SH` varchar(14) DEFAULT NULL,
  `INSCRICAO_MUNICIPAL_SH` varchar(14) DEFAULT NULL,
  `DENOMINACAO_SH` varchar(40) DEFAULT NULL,
  `NOME_PAF_ECF` varchar(40) DEFAULT NULL,
  `VERSAO_PAF_ECF` varchar(10) DEFAULT NULL,
  `MD5_PAF_ECF` varchar(32) DEFAULT NULL,
  `DATA_INICIAL` date DEFAULT NULL,
  `DATA_FINAL` date DEFAULT NULL,
  `VERSAO_ER` varchar(4) DEFAULT NULL,
  `NUMERO_LAUDO_PAF` varchar(40) DEFAULT NULL,
  `RAZAO_SOCIAL_SH` varchar(40) DEFAULT NULL,
  `ENDERECO_SH` varchar(40) DEFAULT NULL,
  `NUMERO_SH` varchar(10) DEFAULT NULL,
  `COMPLEMENTO_SH` varchar(40) DEFAULT NULL,
  `BAIRRO_SH` varchar(40) DEFAULT NULL,
  `CIDADE_SH` varchar(40) DEFAULT NULL,
  `CEP_SH` varchar(8) DEFAULT NULL,
  `UF_SH` char(2) DEFAULT NULL,
  `TELEFONE_SH` varchar(10) DEFAULT NULL,
  `CONTATO_SH` varchar(20) DEFAULT NULL,
  `PRINCIPAL_EXECUTAVEL` varchar(40) DEFAULT NULL,
  `HASH_TRIPA` varchar(32) DEFAULT NULL,
  `HASH_INCREMENTO` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;

/*Table structure for table `r02` */

DROP TABLE IF EXISTS `r02`;

CREATE TABLE `r02` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `ID_OPERADOR` int(10) unsigned NOT NULL,
  `ID_IMPRESSORA` int(10) unsigned NOT NULL,
  `ID_ECF_CAIXA` int(10) unsigned DEFAULT NULL,
  `SERIE_ECF` varchar(20) DEFAULT NULL,
  `CRZ` int(10) unsigned DEFAULT NULL,
  `COO` int(10) unsigned DEFAULT NULL,
  `CRO` int(10) unsigned DEFAULT NULL,
  `DATA_MOVIMENTO` date DEFAULT NULL,
  `DATA_EMISSAO` date DEFAULT NULL,
  `HORA_EMISSAO` varchar(8) DEFAULT NULL,
  `VENDA_BRUTA` decimal(20,6) DEFAULT NULL,
  `GRANDE_TOTAL` decimal(20,6) DEFAULT NULL,
  `SINCRONIZADO` char(1) DEFAULT NULL,
  `HASH_TRIPA` varchar(32) DEFAULT NULL,
  `HASH_INCREMENTO` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;

/*Table structure for table `r03` */

DROP TABLE IF EXISTS `r03`;

CREATE TABLE `r03` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `ID_R02` int(10) unsigned NOT NULL,
  `SERIE_ECF` varchar(20) DEFAULT NULL,
  `CRZ` int(10) unsigned DEFAULT NULL,
  `TOTALIZADOR_PARCIAL` varchar(10) DEFAULT NULL,
  `VALOR_ACUMULADO` decimal(20,6) DEFAULT NULL,
  `SINCRONIZADO` varchar(1) DEFAULT NULL,
  `HASH_TRIPA` varchar(32) DEFAULT NULL,
  `HASH_INCREMENTO` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_R02_R03` (`ID_R02`),
  CONSTRAINT `r03_ibfk_1` FOREIGN KEY (`ID_R02`) REFERENCES `r02` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=21 DEFAULT CHARSET=latin1;

/*Table structure for table `r06` */

DROP TABLE IF EXISTS `r06`;

CREATE TABLE `r06` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `ID_OPERADOR` int(10) unsigned NOT NULL,
  `ID_IMPRESSORA` int(10) unsigned NOT NULL,
  `ID_ECF_CAIXA` int(10) unsigned DEFAULT NULL,
  `SERIE_ECF` varchar(20) DEFAULT NULL,
  `COO` int(10) unsigned DEFAULT NULL,
  `GNF` int(10) unsigned DEFAULT NULL,
  `GRG` int(10) unsigned DEFAULT NULL,
  `CDC` int(10) unsigned DEFAULT NULL,
  `DENOMINACAO` char(2) DEFAULT NULL,
  `DATA_EMISSAO` date DEFAULT NULL,
  `HORA_EMISSAO` varchar(8) DEFAULT NULL,
  `SINCRONIZADO` char(1) DEFAULT NULL,
  `HASH_TRIPA` varchar(32) DEFAULT NULL,
  `HASH_INCREMENTO` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=latin1;

/*Table structure for table `r07` */

DROP TABLE IF EXISTS `r07`;

CREATE TABLE `r07` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `ID_R06` int(10) unsigned DEFAULT NULL,
  `CCF` int(10) unsigned DEFAULT NULL,
  `MEIO_PAGAMENTO` varchar(20) DEFAULT NULL,
  `VALOR_PAGAMENTO` decimal(20,6) DEFAULT NULL,
  `ESTORNO` char(1) DEFAULT NULL,
  `VALOR_ESTORNO` decimal(20,6) DEFAULT NULL,
  `SINCRONIZADO` char(1) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_R06_R07` (`ID_R06`),
  CONSTRAINT `r07_ibfk_1` FOREIGN KEY (`ID_R06`) REFERENCES `r06` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=latin1;

/*Table structure for table `sintegra_60a` */

DROP TABLE IF EXISTS `sintegra_60a`;

CREATE TABLE `sintegra_60a` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `ID_SINTEGRA_60M` int(10) unsigned NOT NULL,
  `SITUACAO_TRIBUTARIA` varchar(4) DEFAULT NULL,
  `VALOR` decimal(20,6) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `SINTEGRA_60A_FKIndex1` (`ID_SINTEGRA_60M`),
  CONSTRAINT `sintegra_60a_ibfk_1` FOREIGN KEY (`ID_SINTEGRA_60M`) REFERENCES `sintegra_60m` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=13 DEFAULT CHARSET=latin1;

/*Table structure for table `sintegra_60m` */

DROP TABLE IF EXISTS `sintegra_60m`;

CREATE TABLE `sintegra_60m` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `DATA_EMISSAO` date DEFAULT NULL,
  `NUMERO_SERIE_ECF` varchar(20) DEFAULT NULL,
  `NUMERO_EQUIPAMENTO` int(10) unsigned DEFAULT NULL,
  `MODELO_DOCUMENTO_FISCAL` char(2) DEFAULT NULL,
  `COO_INICIAL` int(10) unsigned DEFAULT NULL,
  `COO_FINAL` int(10) unsigned DEFAULT NULL,
  `CRZ` int(10) unsigned DEFAULT NULL,
  `CRO` int(10) unsigned DEFAULT NULL,
  `VALOR_VENDA_BRUTA` decimal(20,6) DEFAULT NULL,
  `VALOR_GRANDE_TOTAL` decimal(20,6) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;

/*Table structure for table `situacao_cliente` */

DROP TABLE IF EXISTS `situacao_cliente`;

CREATE TABLE `situacao_cliente` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `NOME` varchar(20) DEFAULT NULL,
  `DESCRICAO` text,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;

/*Table structure for table `unidade_produto` */

DROP TABLE IF EXISTS `unidade_produto`;

CREATE TABLE `unidade_produto` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `NOME` varchar(10) DEFAULT NULL,
  `PODE_FRACIONAR` char(1) DEFAULT NULL,
  `DESCRICAO` text,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=latin1;

/* Trigger structure for table `dav_cabecalho` */

DELIMITER $$

/*!50003 DROP TRIGGER*//*!50032 IF EXISTS */ /*!50003 `HashDavCabecalho` */$$

/*!50003 CREATE */ /*!50017 DEFINER = 'root'@'localhost' */ /*!50003 TRIGGER `HashDavCabecalho` BEFORE UPDATE ON `dav_cabecalho` FOR EACH ROW BEGIN
	SET NEW.HASH_INCREMENTO = NEW.HASH_INCREMENTO + 1;
    END */$$


DELIMITER ;

/* Trigger structure for table `dav_detalhe` */

DELIMITER $$

/*!50003 DROP TRIGGER*//*!50032 IF EXISTS */ /*!50003 `HashDavDetalhe` */$$

/*!50003 CREATE */ /*!50017 DEFINER = 'root'@'localhost' */ /*!50003 TRIGGER `HashDavDetalhe` BEFORE UPDATE ON `dav_detalhe` FOR EACH ROW BEGIN
	SET NEW.HASH_INCREMENTO = NEW.HASH_INCREMENTO + 1;
    END */$$


DELIMITER ;

/* Trigger structure for table `ecf_estoque` */

DELIMITER $$

/*!50003 DROP TRIGGER*//*!50032 IF EXISTS */ /*!50003 `HashEstoque` */$$

/*!50003 CREATE */ /*!50017 DEFINER = 'root'@'localhost' */ /*!50003 TRIGGER `HashEstoque` BEFORE UPDATE ON `ecf_estoque` FOR EACH ROW BEGIN
	SET NEW.HASH_INCREMENTO = NEW.HASH_INCREMENTO + 1;
    END */$$


DELIMITER ;

/* Trigger structure for table `ecf_total_tipo_pgto` */

DELIMITER $$

/*!50003 DROP TRIGGER*//*!50032 IF EXISTS */ /*!50003 `HashTotalTipoPgto` */$$

/*!50003 CREATE */ /*!50017 DEFINER = 'root'@'localhost' */ /*!50003 TRIGGER `HashTotalTipoPgto` BEFORE UPDATE ON `ecf_total_tipo_pgto` FOR EACH ROW BEGIN
	SET NEW.HASH_INCREMENTO = NEW.HASH_INCREMENTO + 1;
    END */$$


DELIMITER ;

/* Trigger structure for table `ecf_venda_cabecalho` */

DELIMITER $$

/*!50003 DROP TRIGGER*//*!50032 IF EXISTS */ /*!50003 `HashVendaCabecalho` */$$

/*!50003 CREATE */ /*!50017 DEFINER = 'root'@'localhost' */ /*!50003 TRIGGER `HashVendaCabecalho` BEFORE UPDATE ON `ecf_venda_cabecalho` FOR EACH ROW BEGIN
	SET NEW.HASH_INCREMENTO = NEW.HASH_INCREMENTO + 1;
    END */$$


DELIMITER ;

/* Trigger structure for table `ecf_venda_detalhe` */

DELIMITER $$

/*!50003 DROP TRIGGER*//*!50032 IF EXISTS */ /*!50003 `HashVendaDetalhe` */$$

/*!50003 CREATE */ /*!50017 DEFINER = 'root'@'localhost' */ /*!50003 TRIGGER `HashVendaDetalhe` BEFORE UPDATE ON `ecf_venda_detalhe` FOR EACH ROW BEGIN
	SET NEW.HASH_INCREMENTO = NEW.HASH_INCREMENTO + 1;
    END */$$


DELIMITER ;

/* Trigger structure for table `produto` */

DELIMITER $$

/*!50003 DROP TRIGGER*//*!50032 IF EXISTS */ /*!50003 `HashProduto` */$$

/*!50003 CREATE */ /*!50017 DEFINER = 'root'@'localhost' */ /*!50003 TRIGGER `HashProduto` BEFORE UPDATE ON `produto` FOR EACH ROW BEGIN
	SET NEW.HASH_INCREMENTO = NEW.HASH_INCREMENTO + 1;
    END */$$


DELIMITER ;

/* Trigger structure for table `r01` */

DELIMITER $$

/*!50003 DROP TRIGGER*//*!50032 IF EXISTS */ /*!50003 `HashR01` */$$

/*!50003 CREATE */ /*!50017 DEFINER = 'root'@'localhost' */ /*!50003 TRIGGER `HashR01` BEFORE UPDATE ON `r01` FOR EACH ROW BEGIN
	SET NEW.HASH_INCREMENTO = NEW.HASH_INCREMENTO + 1;
    END */$$


DELIMITER ;

/* Trigger structure for table `r02` */

DELIMITER $$

/*!50003 DROP TRIGGER*//*!50032 IF EXISTS */ /*!50003 `HashR02` */$$

/*!50003 CREATE */ /*!50017 DEFINER = 'root'@'localhost' */ /*!50003 TRIGGER `HashR02` BEFORE UPDATE ON `r02` FOR EACH ROW BEGIN
	SET NEW.HASH_INCREMENTO = NEW.HASH_INCREMENTO + 1;
    END */$$


DELIMITER ;

/* Trigger structure for table `r03` */

DELIMITER $$

/*!50003 DROP TRIGGER*//*!50032 IF EXISTS */ /*!50003 `HashR03` */$$

/*!50003 CREATE */ /*!50017 DEFINER = 'root'@'localhost' */ /*!50003 TRIGGER `HashR03` BEFORE UPDATE ON `r03` FOR EACH ROW BEGIN
	SET NEW.HASH_INCREMENTO = NEW.HASH_INCREMENTO + 1;
    END */$$


DELIMITER ;

/* Trigger structure for table `r06` */

DELIMITER $$

/*!50003 DROP TRIGGER*//*!50032 IF EXISTS */ /*!50003 `HashR06` */$$

/*!50003 CREATE */ /*!50017 DEFINER = 'root'@'localhost' */ /*!50003 TRIGGER `HashR06` BEFORE UPDATE ON `r06` FOR EACH ROW BEGIN
	SET NEW.HASH_INCREMENTO = NEW.HASH_INCREMENTO + 1;
    END */$$


DELIMITER ;

/*Table structure for table `view_60d` */

DROP TABLE IF EXISTS `view_60d`;

/*!50001 DROP VIEW IF EXISTS `view_60d` */;
/*!50001 DROP TABLE IF EXISTS `view_60d` */;

/*!50001 CREATE TABLE  `view_60d`(
 `GTIN` varchar(14) ,
 `SERIE` varchar(20) ,
 `DATA_EMISSAO` date ,
 `ID` int(10) unsigned ,
 `ECF_ICMS_ST` varchar(4) ,
 `SOMA_QUANTIDADE` decimal(42,6) ,
 `SOMA_ITEM` decimal(42,6) ,
 `SOMA_BASE_ICMS` decimal(42,6) ,
 `SOMA_ICMS` decimal(42,6) 
)*/;

/*Table structure for table `view_60r` */

DROP TABLE IF EXISTS `view_60r`;

/*!50001 DROP VIEW IF EXISTS `view_60r` */;
/*!50001 DROP TABLE IF EXISTS `view_60r` */;

/*!50001 CREATE TABLE  `view_60r`(
 `GTIN` varchar(14) ,
 `SERIE` varchar(20) ,
 `DATA_EMISSAO` date ,
 `MES_EMISSAO` int(2) ,
 `ANO_EMISSAO` int(4) ,
 `ID` int(10) unsigned ,
 `ECF_ICMS_ST` varchar(4) ,
 `SOMA_QUANTIDADE` decimal(42,6) ,
 `SOMA_ITEM` decimal(42,6) ,
 `SOMA_BASE_ICMS` decimal(42,6) ,
 `SOMA_ICMS` decimal(42,6) 
)*/;

/*Table structure for table `view_61r` */

DROP TABLE IF EXISTS `view_61r`;

/*!50001 DROP VIEW IF EXISTS `view_61r` */;
/*!50001 DROP TABLE IF EXISTS `view_61r` */;

/*!50001 CREATE TABLE  `view_61r`(
 `GTIN` varchar(14) ,
 `DATA_EMISSAO` date ,
 `MES_EMISSAO` int(2) ,
 `ANO_EMISSAO` int(4) ,
 `ECF_ICMS_ST` varchar(4) ,
 `SOMA_QUANTIDADE` decimal(42,6) ,
 `SOMA_ITEM` decimal(42,6) ,
 `SOMA_BASE_ICMS` decimal(42,6) 
)*/;

/*Table structure for table `view_r04` */

DROP TABLE IF EXISTS `view_r04`;

/*!50001 DROP VIEW IF EXISTS `view_r04` */;
/*!50001 DROP TABLE IF EXISTS `view_r04` */;

/*!50001 CREATE TABLE  `view_r04`(
 `VCID` int(10) unsigned ,
 `ID_ECF_MOVIMENTO` int(10) unsigned ,
 `SERIE_ECF` varchar(20) ,
 `CCF` int(10) unsigned ,
 `COO` int(10) unsigned ,
 `DATA_VENDA` date ,
 `VALOR_VENDA` decimal(20,6) ,
 `HASH_TRIPA` varchar(32) ,
 `HASH_INCREMENTO` int(11) ,
 `DESCONTO` decimal(20,6) ,
 `ACRESCIMO` decimal(20,6) ,
 `VALOR_FINAL` decimal(20,6) ,
 `STATUS_VENDA` char(1) ,
 `CUPOM_CANCELADO` char(1) ,
 `NOME_CLIENTE` varchar(100) ,
 `PIS` decimal(20,6) ,
 `COFINS` decimal(20,6) ,
 `CPF_CNPJ_CLIENTE` varchar(14) ,
 `MID` int(10) unsigned ,
 `ID_ECF_IMPRESSORA` int(10) unsigned ,
 `ID_ECF_OPERADOR` int(10) unsigned 
)*/;

/*Table structure for table `view_r05` */

DROP TABLE IF EXISTS `view_r05`;

/*!50001 DROP VIEW IF EXISTS `view_r05` */;
/*!50001 DROP TABLE IF EXISTS `view_r05` */;

/*!50001 CREATE TABLE  `view_r05`(
 `VCID` int(10) unsigned ,
 `VID` int(10) unsigned ,
 `ITEM` int(10) unsigned ,
 `SERIE_ECF` varchar(20) ,
 `GTIN` varchar(14) ,
 `CCF` int(10) unsigned ,
 `COO` int(10) unsigned ,
 `DESCRICAO_PDV` varchar(30) ,
 `QUANTIDADE` decimal(20,6) ,
 `CST` char(3) ,
 `PIS` decimal(20,6) ,
 `COFINS` decimal(20,6) ,
 `HASH_TRIPA` varchar(32) ,
 `HASH_INCREMENTO` int(11) ,
 `SIGLA_UNIDADE` varchar(10) ,
 `VALOR_UNITARIO` decimal(20,6) ,
 `DESCONTO` decimal(20,6) ,
 `ACRESCIMO` decimal(20,6) ,
 `CFOP` int(10) unsigned ,
 `TAXA_ICMS` decimal(20,6) ,
 `ID_ECF_PRODUTO` int(10) unsigned ,
 `TOTAL_ITEM` decimal(20,6) ,
 `TOTALIZADOR_PARCIAL` varchar(10) ,
 `CANCELADO` char(1) ,
 `IAT` char(1) ,
 `IPPT` char(1) ,
 `ID_UNIDADE` int(10) unsigned 
)*/;

/*View structure for view view_60d */

/*!50001 DROP TABLE IF EXISTS `view_60d` */;
/*!50001 DROP VIEW IF EXISTS `view_60d` */;

/*!50001 CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `view_60d` AS (select `vd`.`GTIN` AS `GTIN`,`i`.`SERIE` AS `SERIE`,`vc`.`DATA_VENDA` AS `DATA_EMISSAO`,`m`.`ID` AS `ID`,`vd`.`ECF_ICMS_ST` AS `ECF_ICMS_ST`,sum(`vd`.`QUANTIDADE`) AS `SOMA_QUANTIDADE`,sum(`vd`.`VALOR_TOTAL`) AS `SOMA_ITEM`,sum(`vd`.`BASE_ICMS`) AS `SOMA_BASE_ICMS`,sum(`vd`.`ICMS`) AS `SOMA_ICMS` from (((`ecf_venda_cabecalho` `vc` join `ecf_venda_detalhe` `vd`) join `ecf_impressora` `i`) join `ecf_movimento` `m`) where ((`vc`.`ID_ECF_MOVIMENTO` = `m`.`ID`) and (`m`.`ID_ECF_IMPRESSORA` = `i`.`ID`) and (`vd`.`ID_ECF_VENDA_CABECALHO` = `vc`.`ID`) and (`vd`.`CANCELADO` = 'N')) group by `vd`.`GTIN`,`i`.`SERIE`,`vc`.`DATA_VENDA`,`m`.`ID`,`vd`.`ECF_ICMS_ST`) */;

/*View structure for view view_60r */

/*!50001 DROP TABLE IF EXISTS `view_60r` */;
/*!50001 DROP VIEW IF EXISTS `view_60r` */;

/*!50001 CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `view_60r` AS (select `vd`.`GTIN` AS `GTIN`,`i`.`SERIE` AS `SERIE`,`vc`.`DATA_VENDA` AS `DATA_EMISSAO`,month(`vc`.`DATA_VENDA`) AS `MES_EMISSAO`,year(`vc`.`DATA_VENDA`) AS `ANO_EMISSAO`,`m`.`ID` AS `ID`,`vd`.`ECF_ICMS_ST` AS `ECF_ICMS_ST`,sum(`vd`.`QUANTIDADE`) AS `SOMA_QUANTIDADE`,sum(`vd`.`VALOR_TOTAL`) AS `SOMA_ITEM`,sum(`vd`.`BASE_ICMS`) AS `SOMA_BASE_ICMS`,sum(`vd`.`ICMS`) AS `SOMA_ICMS` from (((`ecf_venda_cabecalho` `vc` join `ecf_venda_detalhe` `vd`) join `ecf_impressora` `i`) join `ecf_movimento` `m`) where ((`vc`.`ID_ECF_MOVIMENTO` = `m`.`ID`) and (`m`.`ID_ECF_IMPRESSORA` = `i`.`ID`) and (`vd`.`ID_ECF_VENDA_CABECALHO` = `vc`.`ID`)) group by month(`vc`.`DATA_VENDA`),year(`vc`.`DATA_VENDA`),`vd`.`GTIN`) */;

/*View structure for view view_61r */

/*!50001 DROP TABLE IF EXISTS `view_61r` */;
/*!50001 DROP VIEW IF EXISTS `view_61r` */;

/*!50001 CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `view_61r` AS (select `p`.`GTIN` AS `GTIN`,`nf2c`.`DATA_EMISSAO` AS `DATA_EMISSAO`,month(`nf2c`.`DATA_EMISSAO`) AS `MES_EMISSAO`,year(`nf2c`.`DATA_EMISSAO`) AS `ANO_EMISSAO`,`nf2d`.`ECF_ICMS_ST` AS `ECF_ICMS_ST`,sum(`nf2d`.`QUANTIDADE`) AS `SOMA_QUANTIDADE`,sum(`nf2d`.`VALOR_TOTAL`) AS `SOMA_ITEM`,sum(`nf2d`.`BASE_ICMS`) AS `SOMA_BASE_ICMS` from ((`nota_fiscal_cabecalho` `nf2c` join `nota_fiscal_detalhe` `nf2d`) join `produto` `p`) where ((`nf2d`.`ID_PRODUTO` = `p`.`ID`) and (`nf2d`.`ID_NF_CABECALHO` = `nf2c`.`ID`)) group by month(`nf2c`.`DATA_EMISSAO`),year(`nf2c`.`DATA_EMISSAO`),`p`.`GTIN`,`p`.`ECF_ICMS_ST`) */;

/*View structure for view view_r04 */

/*!50001 DROP TABLE IF EXISTS `view_r04` */;
/*!50001 DROP VIEW IF EXISTS `view_r04` */;

/*!50001 CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `view_r04` AS (select `vc`.`ID` AS `VCID`,`vc`.`ID_ECF_MOVIMENTO` AS `ID_ECF_MOVIMENTO`,`vc`.`SERIE_ECF` AS `SERIE_ECF`,`vc`.`CCF` AS `CCF`,`vc`.`COO` AS `COO`,`vc`.`DATA_VENDA` AS `DATA_VENDA`,`vc`.`VALOR_VENDA` AS `VALOR_VENDA`,`vc`.`HASH_TRIPA` AS `HASH_TRIPA`,`vc`.`HASH_INCREMENTO` AS `HASH_INCREMENTO`,`vc`.`DESCONTO` AS `DESCONTO`,`vc`.`ACRESCIMO` AS `ACRESCIMO`,`vc`.`VALOR_FINAL` AS `VALOR_FINAL`,`vc`.`STATUS_VENDA` AS `STATUS_VENDA`,`vc`.`CUPOM_CANCELADO` AS `CUPOM_CANCELADO`,`vc`.`NOME_CLIENTE` AS `NOME_CLIENTE`,`vc`.`PIS` AS `PIS`,`vc`.`COFINS` AS `COFINS`,`vc`.`CPF_CNPJ_CLIENTE` AS `CPF_CNPJ_CLIENTE`,`m`.`ID` AS `MID`,`m`.`ID_ECF_IMPRESSORA` AS `ID_ECF_IMPRESSORA`,`m`.`ID_ECF_OPERADOR` AS `ID_ECF_OPERADOR` from (`ecf_venda_cabecalho` `vc` join `ecf_movimento` `m`) where (`vc`.`ID_ECF_MOVIMENTO` = `m`.`ID`)) */;

/*View structure for view view_r05 */

/*!50001 DROP TABLE IF EXISTS `view_r05` */;
/*!50001 DROP VIEW IF EXISTS `view_r05` */;

/*!50001 CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `view_r05` AS (select `vc`.`ID` AS `VCID`,`v`.`ID` AS `VID`,`v`.`ITEM` AS `ITEM`,`v`.`SERIE_ECF` AS `SERIE_ECF`,`v`.`GTIN` AS `GTIN`,`v`.`CCF` AS `CCF`,`v`.`COO` AS `COO`,`p`.`DESCRICAO_PDV` AS `DESCRICAO_PDV`,`v`.`QUANTIDADE` AS `QUANTIDADE`,`v`.`CST` AS `CST`,`v`.`PIS` AS `PIS`,`v`.`COFINS` AS `COFINS`,`v`.`HASH_TRIPA` AS `HASH_TRIPA`,`v`.`HASH_INCREMENTO` AS `HASH_INCREMENTO`,`u`.`NOME` AS `SIGLA_UNIDADE`,`v`.`VALOR_UNITARIO` AS `VALOR_UNITARIO`,`v`.`DESCONTO` AS `DESCONTO`,`v`.`ACRESCIMO` AS `ACRESCIMO`,`v`.`CFOP` AS `CFOP`,`v`.`TAXA_ICMS` AS `TAXA_ICMS`,`v`.`ID_ECF_PRODUTO` AS `ID_ECF_PRODUTO`,`v`.`TOTAL_ITEM` AS `TOTAL_ITEM`,`v`.`TOTALIZADOR_PARCIAL` AS `TOTALIZADOR_PARCIAL`,`v`.`CANCELADO` AS `CANCELADO`,`p`.`IAT` AS `IAT`,`p`.`IPPT` AS `IPPT`,`p`.`ID_UNIDADE_PRODUTO` AS `ID_UNIDADE` from (((`ecf_venda_cabecalho` `vc` join `ecf_venda_detalhe` `v`) join `produto` `p`) join `unidade_produto` `u`) where ((`vc`.`ID` = `v`.`ID_ECF_VENDA_CABECALHO`) and (`v`.`ID_ECF_PRODUTO` = `p`.`ID`) and (`p`.`ID_UNIDADE_PRODUTO` = `u`.`ID`))) */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
